# Generated by Django 3.1.6 on 2021-02-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('OPEN', 'OPEN'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC'), ('NT', 'NT')], max_length=100)),
                ('academic_class', models.CharField(max_length=8)),
                ('roll_no', models.IntegerField(unique=True)),
                ('division', models.IntegerField()),
                ('date_of_birth', models.DateField(max_length=50)),
                ('years', models.IntegerField()),
                ('months', models.IntegerField()),
                ('residential_addr', models.CharField(max_length=755)),
                ('taluka', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('journey_from', models.CharField(max_length=50)),
                ('journey_to', models.CharField(max_length=50)),
                ('via', models.CharField(blank=True, max_length=50, null=True)),
                ('railway_line', models.CharField(choices=[('Central Railways', 'Central Railways'), ('Western Railways', 'Western Railways')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railway_class', models.CharField(choices=[('First Class', 'First Class'), ('Second Class', 'Second Class')], max_length=100)),
                ('duration', models.CharField(choices=[('Monthly', 'Monthly'), ('Quaterly', 'Quaterly')], max_length=100)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('journey_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='ERCP_APP.carddetail')),
                ('journey_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='ERCP_APP.carddetail')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_details', to=settings.AUTH_USER_MODEL)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_name', to='ERCP_APP.carddetail')),
                ('via', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='via_source', to='ERCP_APP.carddetail')),
            ],
        ),
        migrations.AddField(
            model_name='carddetail',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
