# Generated by Django 3.1.6 on 2021-02-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERCP_APP', '0002_auto_20210204_0007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardDetails',
            new_name='CardDetails',
        ),
        migrations.RenameModel(
            old_name='FormDetails',
            new_name='FormDetails',
        ),
    ]
