# Generated by Django 3.1.6 on 2021-02-03 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERCP_APP', '0003_auto_20210204_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railway_class', models.CharField(choices=[('First Class', 'First Class'), ('Second Class', 'Second Class')], max_length=100)),
                ('duration', models.CharField(choices=[('Monthly', 'Monthly'), ('Quaterly', 'Quaterly')], max_length=100)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('OPEN', 'OPEN'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC'), ('NT', 'NT')], max_length=100)),
                ('academic_class', models.CharField(max_length=8)),
                ('roll_no', models.IntegerField(unique=True)),
                ('division', models.IntegerField()),
                ('date_of_birth', models.DateField(max_length=50)),
                ('years', models.IntegerField()),
                ('months', models.IntegerField()),
                ('residential_addr', models.CharField(max_length=755)),
                ('taluka', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('journey_from', models.CharField(max_length=50)),
                ('journey_to', models.CharField(max_length=50)),
                ('via', models.CharField(blank=True, max_length=50, null=True)),
                ('railway_line', models.CharField(choices=[('Central Railways', 'Central Railways'), ('Western Railways', 'Western Railways')], max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
