# Generated by Django 3.1.6 on 2021-02-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERCP_APP', '0005_auto_20210204_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdetail',
            old_name='user_name',
            new_name='user_card',
        ),
        migrations.RemoveField(
            model_name='formdetail',
            name='journey_from',
        ),
        migrations.RemoveField(
            model_name='formdetail',
            name='journey_to',
        ),
        migrations.RemoveField(
            model_name='formdetail',
            name='via',
        ),
    ]
