# Generated by Django 3.1.6 on 2021-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERCP_APP', '0006_auto_20210204_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_card',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
