# Generated by Django 3.1.6 on 2021-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERCP_APP', '0007_user_has_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetail',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carddetail',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
